export const CURRENT_LOCATION='CURRENT_LOCATION';
export const SHOP_LOCATION='SHOP_LOCATION';
export const CUSTOMER_LOCATION='CUSTOMER_LOCATION';
export const AUTH_START='AUTH_START';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const REACH_SHOP='REACH_SHOP';